name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Executa uma vez por dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        with:
          user_name: shimarrudz
          theme: "night-green"
      - name: Commit & Push
        run: |
          git config --global user.email "vic.shima.vss@gmail.com"
          git config --global user.name "shimarrudz"
          git add -A .
          git commit -m "update 3d profile"
          git push
